# Generated by Django 6.0.3 on 2026-03-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titolo", models.CharField(max_length=200)),
                ("autore", models.CharField(max_length=200)),
                ("descrizione", models.TextField(blank=True)),
                ("prezzo", models.DecimalField(decimal_places=2, max_digits=6)),
                ("disponibile", models.BooleanField(default=True)),
                ("aggiunto_il", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
